### PR TITLE
Create courses test

### PR DESCRIPTION
**Pull request by theflickerman404**

### CODE REVIEW

**Review by theflickerman404 — COMMENTED** [review]
I see that you've removed the dependencies on InMemoryCourseDataAccessObject, which is great, please also delete the file.

**Comment by Toyakki** [comment]
Thanks for starting the interactor tests :)

**Comment by yeddddy** [comment]
done, merge if looks good for you guys :)

**Review by theflickerman404 — COMMENTED** [review]
Everything looks good, thanks for making the changes!

**Pull request merged**
