### PR TITLE
SubmitAssignment usecase modifications.

### PR DESCRIPTION
**Pull request by Toyakki**

### CODE REVIEW

**Comment by yeddddy** [comment]
Good job with this implementation! Really good use of the try-and-catch blocks! (I believe I could've used more of them in my tests even though it can get a bit complicated for my use cases)

Two things we can probably talk about later:
1. I don't quite understand your modification for dropboxPath, given that I don't see any changes in the methods in the Assignment class. So by changing this manually created path, I'd assume you'd have to make sure it matches the formate of the path generated in the original method.
2. I'm pretty sure we can defer the error handling to the presenter class? At least that's what I did for my use cases. 

Great work! :p

**Review by theflickerman404 — CHANGES_REQUESTED** [review]
- Your changes to the Assignment entity look good.
- In the SubmitAssignmentController and the like you're directly using the Assignment entity, which violates Clean Architecture, if you want to pass more data through and/or to different parts, implement some sort of input output data scheme (as in the adapter pattern) through the use case interactor, as only that layer can depend explicitly on the business entities. I'd recommend pulling this data using the courseName and assignmentName from the relevant data access interface
- In TeacherDownloadInteractor you are catching an Exception, this is dangerous. Please  narrow down the kind of exception you're catching or remove the check entirely
- Interfaces all look good

**Review by theflickerman404 — CHANGES_REQUESTED** [review]
- JUnit dependency looks good
- Test skeleton looks good
- Your interactor constructor cannot take an Account as an arguement, it should have methods for getting and setting its user, but the interactor itself should be able to be created independent of whichever account is logged in / when the app is built
- In particular, you may want the controller to pass in the email and give the interactor a UserDataAccessObject to pull up the account

**Review by theflickerman404 — CHANGES_REQUESTED** [review]
the memory object should be passed as an argument in the constructor, if you instantiate a new memory object it will be out of sync with the whole program, among other issues

**Review by theflickerman404 — CHANGES_REQUESTED** [review]
- Why does fileExistsByPath in the in memory data access object throw an error? If the file doesn't exist then shouldn't it just return false?
- submit assignment shouldn't take the memory object as an argument, rather it should be passed to the constructor and stored as an instance attribute, see Main.java for how creating everything should work
- In SubmitAssignmentInteractor, you shouldn't catch a general exception, this is dangerous and makes debugging difficult, either catch a more specific exception or introduce methods to handle error handling without a try catch block
- presentSuccessView probably doesn't need a success message, you can just call what needs to be called
- General feedback, if you want to put a temporary class in for development purposes, you really should either make an interface they both implement or just leave swathes of it empty temporarily
- Test skeletons looks good for now

**Review by theflickerman404 — APPROVED** [review]
Perfect, thank you

**Pull request merged**
